### PR TITLE
Solved Issue #32

### PR DESCRIPTION
**Pull request by AjaysinhRajput2802**
I have added volume tweaker, which is working fine.

### CODE REVIEW

**Comment by sanket143** [comment]
@AjaysinhRajput2802 Solve the linting errors which are failing.

**Comment by AjaysinhRajput2802** [comment]
@sanket143 I have fixed all linting errors

**Comment by AjaysinhRajput2802** [comment]
@sanket143 @janvig please review this PR.

**Review by sanket143 — APPROVED** [review]

**Comment by sanket143** [comment]
give @AjaysinhRajput2802 75 points

**Pull request merged**
