### PR TITLE
Solved Issue #21

### LINKED ISSUE #21: Server to serve music files on network
**Note:** This issue is reserved for SLoP Contributors.

Using ExpressJS, should serve files from the directory configured by the user in settings.

### PR DESCRIPTION
**Pull request by AjaysinhRajput2802**

### CODE REVIEW

**Comment by AjaysinhRajput2802** [comment]
@sanket143 @janvig please review this PR.

**Comment by sanket143** [comment]
give @AjaysinhRajput2802 150 points

**Comment by abhinavraj23** [comment]
@sanket143 don't u think this PR deserves about 75 points as it has major changes in package-lock.json which is autogenerated and rest is just 31 lines of code.

**Comment by sanket143** [comment]
@abhinavraj23  From the looks of the issue, a very trivial approach was to use a static server but that would just work for the single folder and also it would've exposed other files along with the .mp3s to the network. This PR was able to limit the files exposed to the network to just .mp3 and also it was able to serve all .mp3 files which were detected by MJam and not just of one directory.

Actually, I can agree with you on this one but the author of this PR had little to no experience in servers or express.js and so there was a lot of time and efforts were put in to come up with this solution at the end. Still, 150 does seem too much for this PR but there were no in-between 75 or 150. So, at the end decided to give 150.

**Pull request merged**
