### PR TITLE
Fixed Issue #41

### LINKED ISSUE #41: Unable to play the first song
The first song on the list cannot be played unless another song on the list has been played at least once.

### PR DESCRIPTION
**Pull request by AjaysinhRajput2802**
By adding one condition, when we are reading file, If nowplaying.instance is not there then load first song in data to play first song.

### CODE REVIEW

**Comment by AjaysinhRajput2802** [comment]
@sanket143 @janvig please review this PR.

**Review by sanket143 — APPROVED** [review]

**Comment by sanket143** [comment]
give @AjaysinhRajput2802 75 points

**Comment by abhinavraj23** [comment]
@sanket143 this was just an if condition and refactoring, how about 25 points in this one?

**Comment by sanket143** [comment]
@abhinavraj23 it was an actual bug and there was no proper direction. Though it is a little change, it is solving a big issue. Also, it's harder to figure out without any error messages.
This PR suggests loading the first song if the instance is undefined. There were a lot of ways to tackle this issue and he just happened to find out the slickest one. This being an actual bug demands a good understanding of the codebase and a lot of debugging to figure out a solution on their own without much guidance.

**Pull request merged**
