### PR TITLE
Fixed Issue #42

### LINKED ISSUE #42: "TypeError: state.nowplaying.instance.loop is not a function"
Console error while rendering the _Now Playing_ bar when there is no song in the recent list.

### PR DESCRIPTION
**Pull request by AjaysinhRajput2802**

### CODE REVIEW

**Comment by AjaysinhRajput2802** [comment]
@sanket143 @janvig  Please Review this one, so I can make other PR for other Issue..

**Comment by sanket143** [comment]
@AjaysinhRajput2802 look into the checks which are failing, it's most likely the linting errors. Try to fix those and rest LGTM

**Comment by AjaysinhRajput2802** [comment]
@sanket143 I have fixed all linting errors

**Review by sanket143 — APPROVED** [review]

**Comment by AjaysinhRajput2802** [comment]
@sanket143 @janvig If this PR is valid then, can you please give me points for this ?

**Comment by sanket143** [comment]
give @AjaysinhRajput2802 75 points

**Comment by abhinavraj23** [comment]
@sanket143 same as previous comments on PRs, this one also has just one if statement

**Comment by sanket143** [comment]
This is also similar to this [PR](https://github.com/sanket143/MJam/pull/65) is solving an actual bug. In addition to [this](https://github.com/sanket143/MJam/pull/65#issuecomment-735398358) comment, this was also a critical one because it was causing the player to crash. It's severity made it worth more.

**Pull request merged**
